services:
  escape.installer:
    image: node:20
    command: npm install
    volumes:
      - ./:/app
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    restart: no

  escape.server:
    image: node:20
    command: npm run start
    volumes:
      - ./:/app
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3000:3000"
    depends_on:
      escape.installer:
        condition: service_completed_successfully
